const data = {
  products: [
    {
      name: "맨시티 홈 상의",
      slug: "mancity-home-shirt",
      category: "Shirts",
      image: "/images/p1.png",
      price: 40000,
      countInStock: 10,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "2022/23 mancity home shirt",
    },
    {
      name: "맨시티 어웨이 상의",
      slug: "mancity-away-shirt",
      category: "Shirts",
      image: "/images/p2.png",
      price: 20000,
      countInStock: 20,
      brand: "Puma",
      rating: 4.0,
      numReviews: 5,
      description: "2022/23 mancity away shirt",
    },
    {
      name: "맨시티 홈 하의",
      slug: "mancity-home-pants",
      category: "Pants",
      image: "/images/p3.png",
      price: 26000,
      countInStock: 15,
      brand: "Puma",
      rating: 4.7,
      numReviews: 8,
      description: "2022/23 mancity home pants",
    },
    {
      name: "맨시티 어웨이 하의",
      slug: "mancity-away-pants",
      category: "Pants",
      image: "/images/p4.png",
      price: 13000,
      countInStock: 25,
      brand: "Puma",
      rating: 4.8,
      numReviews: 6,
      description: "2022/23 mancity away pants",
    },
  ],
};

export default data;
